spring:
  application:
    name: chat-crawler
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost:27020/chat-crawler}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:password}

tristar:
  chat:
    schedule:
      rate: 10000
    providers:
      telegram:
        url: https://api.telegram.org
        token: insert_token_here

server:
  port: 4141
  servlet:
    context-path: /api/chat-crawler